# Generated by Django 3.1.7 on 2021-04-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('objet', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('is_a_response', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_Mail', models.EmailField(max_length=254, verbose_name=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recherche.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Receiver_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recherche.mail')),
            ],
        ),
        migrations.CreateModel(
            name='Mail_Receiver_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recherche.mail')),
                ('user_mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recherche.user_email')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='mail_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recherche.user_email'),
        ),
    ]
