# Generated by Django 3.1.7 on 2021-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recherche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_receiver_in',
            name='genre',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
