# Generated by Django 3.1.7 on 2021-04-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recherche', '0002_mail_receiver_in_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail_Receiver_in',
            new_name='Mail_Receiver',
        ),
        migrations.DeleteModel(
            name='Mail_Receiver_out',
        ),
    ]
