# Generated by Django 3.1.7 on 2021-04-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recherche', '0003_auto_20210413_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='body',
        ),
    ]
